### ISSUE TITLE
NPMJS.org can't render typescript on markdown

### ISSUE THREAD

**Issue by mtxr** [TCMiranda/joi-extract-type#1]
Npmjs is only able to render javascript.

Readme.md is not being properly rendered there.

## NPMJS:
![image](https://user-images.githubusercontent.com/707561/46679998-7f041980-cbbe-11e8-9ed0-0a8c32c6b30f.png)

## YARN:
![image](https://user-images.githubusercontent.com/707561/46680024-8a574500-cbbe-11e8-999c-a1d813903d9a.png)

**Comment by mtxr** [comment]
Yarn rocks, you know ¯\_(ツ)_/¯

**Comment by TCMiranda** [comment]
We should use ```ts [example](https://raw.githubusercontent.com/btroncone/ngrx-store-localstorage/master/README.md).
