### ISSUE TITLE
Invalid module name in augmentation- index.d.ts

### ISSUE THREAD

**Issue by janders4** [TCMiranda/joi-extract-type#23]
Hi, i'm looking for some help with the following issue:

Using
```
joi-extract-type: 15.0.1
@hapi/joi": 15.1.1
```

I'm importing in with the following: 
`import 'joi-extract-type'`

In the node module file index.d.ts i'm having the following error:
_module "@hapi/joi"
Invalid module name in augmentation. Module '@hapi/joi' resolves to an untyped module at '/Users/johnanderson/Documents/GitHub/error-handling-class-spike/node_modules/@hapi/joi/lib/index.js', which cannot be augmented.ts(2665)_

Thanks

John

**Comment by TCMiranda** [comment]
Uhmm @janders4 can you try installing also @types/hapi__joi ?

**Comment by evanshortiss** [comment]
@TCMiranda I've just run into the same issue. It looks like they've changed the definitions recently so I think it's linked to that.

**Comment by evanshortiss** [comment]
Here's the error I'm seeing:

```
node_modules/joi-extract-type/dist/index.d.ts:9:16 - error TS2649: Cannot augment module 'Joi' with value exports because it resolves to a non-module entity.
```

**Comment by TCMiranda** [comment]
Hello @evanshortiss you are right, i'll update the package.json dependencies to disallow those definitions.

**Comment by TCMiranda** [comment]
Updated on 15.0.2, if you could test on your setup, it would be awesome.
Thanks

**Comment by janders4** [comment]
@TCMiranda, thanks, all is working now
