### ISSUE TITLE
Tagging the Repo

### ISSUE THREAD

**Issue by guyellis** [TCMiranda/joi-extract-type#24]
@TCMiranda I just noticed that `15.0.2` got published a couple of days ago. What were the changes between that and `15.0.1`?

I'm wondering if you could tag the last 3 versions based on their commits in master so that https://github.com/TCMiranda/joi-extract-type/releases has information related to the releases that got published to Npm?

I don't think that anybody else can do this and create a PR because you're the only one that would know which commit you had checked out on master when you ran `npm publish`. Thanks!

**Comment by TCMiranda** [comment]
Hello @guyellis you are right, I need to.
Let me just see if I can start using releases to publish the library with this new github actions thing.
https://github.com/actions/starter-workflows/blob/master/ci/npm-publish.yml

About `15.0.2`, I fixed Joi dependency version to avoid Joi@16 and improved `.default`:
Fixing https://github.com/TCMiranda/joi-extract-type/issues/23 and https://github.com/TCMiranda/joi-extract-type/issues/17
