### ISSUE TITLE
wrong instruction on usage

### ISSUE THREAD

**Issue by allenz8512** [TCMiranda/joi-extract-type#32]
use
`import "joi-extract-type/dist/index" `
instead of
`import './index';`

**Comment by DamodarSojka** [comment]
Actually none of:
`import "joi-extract-type/dist/index";`
import "joi-extract-type/index";
import "./index"; (obviously)
work for me

**Comment by shadrech** [comment]
Same here. Any updates we should be aware of @TCMiranda

**Comment by yinzara** [comment]
i see there are changes in the past 9 days related to TypeScript 3.9 support however I tried to pull these changes and there was no effect. Same error as above.
