### ISSUE TITLE
@hapi/joi package has been deprecated

### ISSUE THREAD

**Issue by justraman** [TCMiranda/joi-extract-type#39]
Author message:
`joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)`.

I am using <https://www.npmjs.com/package/joi> and **joi-extract-type** is incompatible with Joi.

##So when we are going to depend on joi instead of @hapi/joi

**Comment by lonewarrior556** [comment]
joi-extract-type has not been made compatible with Joi 16 yet, 

https://www.npmjs.com/package/joi only has version 17.  And deprecated versions (14)

This will have to be addressed first: https://github.com/TCMiranda/joi-extract-type/issues/22

**Comment by justraman** [comment]
Thank you so much for quick response.
